### ISSUE TITLE
"Ctrl+Tab-ing" - what does it mean? 

### ISSUE THREAD

**Issue by ldm1417** [Stuk/sublime-recent-tab-sort#1]
Not understood...
What does it mean "Ctrl+Tab-ing"?

**Comment by Stuk** [comment]
It means repeatedly pressing Ctrl+Tab to cycle through files (or tabs etc.). 

However I found this extension unreliable, so I actually don’t use it any more. 

Hope that helps!

**Comment by ldm1417** [comment]
This is a default Windows shortcut, which cycle through open programs/apps ...

**Comment by ldm1417** [comment]
Is there a way to change the keybinding for sorting the tabs ?

**Comment by Stuk** [comment]
Ctrl+tab does not cycle through programs on Windows; Alt+tab and Win+tab do though.

Ctrl+tab is the default in Sublime, you can change it with the other keybindings.
